-- CREACIÓN DE TABLAS --

-- REGION --
CREATE TABLE REGION (
  id_region NUMBER(3) NOT NULL,
  nombre VARCHAR2(100) NOT NULL,
  
  CONSTRAINT PK_REGION PRIMARY KEY (id_region),
  CONSTRAINT UN_REGION_NOMBRE UNIQUE (nombre)
);

-- COMUNA --
CREATE TABLE COMUNA (
  id_comuna NUMBER GENERATED ALWAYS AS IDENTITY
              (START WITH 1050 INCREMENT BY 5) NOT NULL,
  nombre VARCHAR2(120) NOT NULL,
  id_region NUMBER(3) NOT NULL,
  
  CONSTRAINT PK_COMUNA PRIMARY KEY (id_comuna),
  CONSTRAINT FK_COMUNA_REGION FOREIGN KEY (id_region) REFERENCES REGION(id_region),
  CONSTRAINT UN_COMUNA_NOMBRE UNIQUE (nombre)
);

-- SISTEMA SALUD--
CREATE TABLE SISTEMA_SALUD (
  id_salud NUMBER(3) NOT NULL,
  nombre VARCHAR2(80) NOT NULL,
  
  CONSTRAINT PK_SALUD PRIMARY KEY (id_salud),
  CONSTRAINT UN_SALUD_NOMBRE UNIQUE (nombre)
);

-- AFP --
CREATE TABLE AFP (
  id_afp NUMBER(3) NOT NULL,
  nombre VARCHAR2(80) NOT NULL,
  
  CONSTRAINT PK_AFP PRIMARY KEY (id_afp),
  CONSTRAINT UN_AFP_NOMBRE UNIQUE (nombre)
);

-- PLANTA --
CREATE TABLE PLANTA (
  id_planta NUMBER(3) NOT NULL,
  nombre VARCHAR2(120) NOT NULL,
  direccion VARCHAR2(200) NOT NULL,
  id_comuna NUMBER NOT NULL,
  
  CONSTRAINT PK_PLANTA PRIMARY KEY (id_planta),
  CONSTRAINT FK_PLANTA_COMUNA FOREIGN KEY (id_comuna) REFERENCES COMUNA(id_comuna)
);

-- TIPO MAQUINA --
CREATE TABLE TIPO_MAQUINA (
  id_tipo_maquina NUMBER(3) NOT NULL,
  nombre VARCHAR2(80) NOT NULL,
  
  CONSTRAINT PK_TIPO_MAQUINA PRIMARY KEY (id_tipo_maquina),
  CONSTRAINT UN_TIPO_MAQUINA_NOMBRE UNIQUE (nombre)
);

-- MAQUINA --
CREATE TABLE MAQUINA (
  nro_maquina NUMBER(3) NOT NULL,
  nombre VARCHAR2(120) NOT NULL,
  activo CHAR(1) DEFAULT 'S' NOT NULL,
  id_planta NUMBER(3) NOT NULL,
  id_tipo_maquina NUMBER(3) NOT NULL,
  
  CONSTRAINT PK_MAQUINA PRIMARY KEY (id_planta, nro_maquina),
  CONSTRAINT FK_MAQUINA_PLANTA FOREIGN KEY (id_planta) REFERENCES PLANTA(id_planta),
  CONSTRAINT FK_MAQUINA_TIPO FOREIGN KEY (id_tipo_maquina) REFERENCES TIPO_MAQUINA(id_tipo_maquina),
  CONSTRAINT CK_MAQUINA_ACTIVO CHECK (activo IN ('S','N'))
);

-- TURNO --
CREATE TABLE TURNO (
  id_turno VARCHAR2(5) NOT NULL,
  nombre VARCHAR2(40) not NULL,
  hora_inicio CHAR(5) NOT NULL,
  hora_termino CHAR(5) NOT NULL,
  
  CONSTRAINT PK_TURNO PRIMARY KEY (id_turno),
  CONSTRAINT UN_TURNO_NOMBRE UNIQUE (nombre),
  CONSTRAINT CK_TURNO_HORA_INI CHECK (REGEXP_LIKE(hora_inicio, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
  CONSTRAINT CK_TURNO_HORA_FIN CHECK (REGEXP_LIKE(hora_termino,'^([01][0-9]|2[0-3]):[0-5][0-9]$'))
);

-- EMPLEADO --
CREATE TABLE EMPLEADO (
  id_empleado NUMBER(3) NOT NULL,
  rut VARCHAR2(12) NOT NULL,
  nombres VARCHAR2(120) NOT NULL,
  apellidos VARCHAR2(120) NOT NULL,
  fecha_contratacion DATE NOT NULL,
  sueldo_base NUMBER(12,2) NOT NULL,
  activo CHAR(1) DEFAULT 'S' NOT NULL,
  id_planta NUMBER(3) NOT NULL,
  id_afp NUMBER(3) NOT NULL,
  id_salud NUMBER(3) NOT NULL,
  id_jefe_directo NUMBER(3) NULL,
  
  CONSTRAINT PK_EMPLEADO PRIMARY KEY (id_empleado),
  CONSTRAINT CK_EMPLEADO_ACTIVO CHECK (activo IN ('S','N')),
  CONSTRAINT FK_EMPLEADO_PLANTA FOREIGN KEY (id_planta) REFERENCES PLANTA(id_planta),
  CONSTRAINT FK_EMPLEADO_AFP FOREIGN KEY (id_afp) REFERENCES AFP(id_afp),
  CONSTRAINT FK_EMPLEADO_SALUD FOREIGN KEY (id_salud) REFERENCES SISTEMA_SALUD(id_salud),
  CONSTRAINT FK_EMPLEADO_EMPLEADO FOREIGN KEY (id_jefe_directo) REFERENCES EMPLEADO(id_empleado)
);

-- JEFE TURNO --
CREATE TABLE JEFE_TURNO (
  id_empleado NUMBER(3) NOT NULL,
  area_responsabilidad VARCHAR2(120) NOT NULL,
  max_operarios NUMBER(3) NOT NULL,
  
  CONSTRAINT PK_JEFE_TRUNO PRIMARY KEY (id_empleado),
  CONSTRAINT FK_JEFE_EMPLEADO FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
);

-- OPERARIO --
CREATE TABLE OPERARIO (
  id_empleado NUMBER(3) NOT NULL,
  categoria_proceso VARCHAR2(30) NOT NULL,
  certificacion VARCHAR2(120),
  horas_estandar_turno NUMBER(2) DEFAULT 8 NOT NULL,
  CONSTRAINT PK_OPERARIO PRIMARY KEY (id_empleado),
  CONSTRAINT FK_OPERARIO_EMPLEADO FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
);

-- TECNICO --
CREATE TABLE TECNICO (
  id_empleado NUMBER(3) NOT NULL,
  especialidad VARCHAR2(30) NOT NULL,
  nivel_certificacion VARCHAR2(60),
  tiempo_respuesta_estandar NUMBER(3) NOT NULL,
  CONSTRAINT PK_TECNICO PRIMARY KEY (id_empleado),
  CONSTRAINT FK_TECNICO_EMPLEADO FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado)
);

-- ASIGNACION TURNO --
CREATE TABLE ASIGNACION_TURNO (
  id_asignacion NUMBER(3) NOT NULL,
  fecha DATE NOT NULL,
  id_empleado NUMBER(3) NOT NULL,
  id_turno VARCHAR2(5) NOT NULL,
  id_planta NUMBER(3) NOT NULL,
  nro_maquina NUMBER(3) NOT NULL,
  rol_turno VARCHAR2(60),
  
  CONSTRAINT PK_ASIGNACION PRIMARY KEY (id_asignacion),
  CONSTRAINT UN_ASIGNACION_EMPLEADO_FECHA UNIQUE (id_empleado, fecha),
  CONSTRAINT FK_ASIGNACION_EMPLEADO FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado),
  CONSTRAINT FK_ASIGNACION_TURNO FOREIGN KEY (id_turno) REFERENCES TURNO(id_turno),
  CONSTRAINT FK_ASIGNACION_MAQUINA FOREIGN KEY (id_planta, nro_maquina) REFERENCES MAQUINA(id_planta, nro_maquina)
);

-- ORDEN MANTENCION --
CREATE TABLE ORDEN_MANTENCION (
  id_orden NUMBER(3) NOT NULL,
  id_planta NUMBER(3) NOT NULL,
  nro_maquina NUMBER(3) NOT NULL,
  id_empleado NUMBER(3) NOT NULL,
  fecha_programada DATE NOT NULL,
  fecha_ejecucion DATE,
  descripcion VARCHAR2(400) NOT NULL,
  
  CONSTRAINT PK_MANTENCION PRIMARY KEY (id_orden),
  CONSTRAINT FK_MANTENCION_MAQUINA  FOREIGN KEY (id_planta, nro_maquina) REFERENCES MAQUINA(id_planta, nro_maquina),
  CONSTRAINT FK_MANTENCION_EMPLEADO  FOREIGN KEY (id_empleado) REFERENCES TECNICO(id_empleado),
  CONSTRAINT CK_MANTENCION_FECHAS CHECK (fecha_ejecucion IS NULL OR fecha_ejecucion >= fecha_programada)
);


-- POBLAMIENTO DE TABLAS --

CREATE SEQUENCE seq_region START WITH 21 INCREMENT BY 1;

INSERT INTO REGION(id_region, nombre) VALUES (seq_region.NEXTVAL, 'Región de Valparaiso');
INSERT INTO REGION(id_region, nombre) VALUES (seq_region.NEXTVAL, 'Región Metropolitana');

INSERT INTO COMUNA(nombre, id_region) VALUES ('Quilpué', 21);
INSERT INTO COMUNA(nombre, id_region) VALUES ('Maipú', 22);

INSERT INTO PLANTA(id_planta, nombre, direccion, id_comuna) VALUES (45, 'Planta Oriente', 'Camino Industrial 1234',1050);
INSERT INTO PLANTA(id_planta, nombre, direccion, id_comuna) VALUES (46, 'Planta Costa', 'Av. Vidrieras 890',1055);

INSERT INTO TURNO(id_turno, nombre, hora_inicio, hora_termino) VALUES ('M0715', 'Mañana', '07:00', '15:00');
INSERT INTO TURNO(id_turno, nombre, hora_inicio, hora_termino) VALUES ('T1523', 'Tarde', '15:00', '23:00');
INSERT INTO TURNO(id_turno, nombre, hora_inicio, hora_termino) VALUES ('N2307', 'Noche', '23:00', '07:00');


-- RECUPERACIÓN DE DATOS --

--INFORME 1 --
SELECT
    (id_turno || ' - ' || nombre) AS "TURNO",
    hora_inicio AS "ENTRADA",
    hora_termino AS "SALIDA"
FROM TURNO
WHERE hora_inicio > '20:00'
ORDER BY hora_inicio DESC;

-- INFORME 2 --
SELECT
    (nombre || ' (' || id_turno || ')') AS "TURNO",
    hora_inicio AS "ENTRADA",
    hora_termino AS "SALIDA"
FROM TURNO
WHERE hora_inicio BETWEEN '06:00' AND '14:59'
ORDER BY hora_inicio;


/*
DROP TABLE ORDEN_MANTENCION CASCADE CONSTRAINTS;
DROP TABLE ASIGNACION_TURNO CASCADE CONSTRAINTS;
DROP TABLE TECNICO CASCADE CONSTRAINTS;
DROP TABLE OPERARIO CASCADE CONSTRAINTS;
DROP TABLE JEFE_TURNO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE MAQUINA CASCADE CONSTRAINTS;
DROP TABLE TIPO_MAQUINA CASCADE CONSTRAINTS;
DROP TABLE PLANTA CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE SISTEMA_SALUD CASCADE CONSTRAINTS;
DROP TABLE AFP CASCADE CONSTRAINTS;
DROP TABLE TURNO CASCADE CONSTRAINTS;
DROP SEQUENCE seq_region;
*/