/*
DROP TABLE dominio CASCADE CONSTRAINTS;
DROP TABLE personal CASCADE CONSTRAINTS;
DROP TABLE titulacion CASCADE CONSTRAINTS;
DROP TABLE titulo CASCADE CONSTRAINTS;
DROP TABLE estado_civil CASCADE CONSTRAINTS;
DROP TABLE genero CASCADE CONSTRAINTS;
DROP TABLE compania CASCADE CONSTRAINTS;
DROP TABLE comuna CASCADE CONSTRAINTS;
DROP TABLE region CASCADE CONSTRAINTS;
DROP TABLE idioma CASCADE CONSTRAINTS;
*/

/* =======================================================
   PRY2204 - Exp3 - Semana 7 (formato estandarizado)
   ======================================================= */

/* ------------------------------------------
   CASO 1: CREACIÓN DEL MODELO RELACIONAL
   ------------------------------------------ */

CREATE TABLE region (
    id_region NUMBER(2)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 7 INCREMENT BY 2 ) NOT NULL,
    nombre    VARCHAR2(25) NOT NULL,
    CONSTRAINT pk_region PRIMARY KEY ( id_region ),
    CONSTRAINT un_region UNIQUE ( nombre )
);

CREATE TABLE comuna (
    id_comuna NUMBER(5) NOT NULL,
    nombre    VARCHAR2(25) NOT NULL,
    id_region NUMBER(2) NOT NULL,
    CONSTRAINT pk_comuna PRIMARY KEY ( id_comuna ),
    CONSTRAINT un_comuna UNIQUE ( nombre ),
    CONSTRAINT fk_comuna_region FOREIGN KEY ( id_region )
        REFERENCES region ( id_region )
);

CREATE TABLE compania (
    id_empresa NUMBER(2) NOT NULL,
    nombre VARCHAR2(25) NOT NULL,
    calle VARCHAR2(50),
    numero  VARCHAR2(5),
    renta NUMBER(10) NOT NULL,
    porcentaje_aumento NUMBER(4, 3) DEFAULT 0,
    id_comuna NUMBER(5) NOT NULL,
    CONSTRAINT pk_compania PRIMARY KEY ( id_empresa ),
    CONSTRAINT un_compania UNIQUE ( nombre ),
    CONSTRAINT fk_compania_comuna FOREIGN KEY ( id_comuna )
        REFERENCES comuna ( id_comuna )
);

CREATE TABLE idioma (
    id_idioma NUMBER(3)
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 25 INCREMENT BY 3 ) NOT NULL,
    nombre VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_idioma PRIMARY KEY ( id_idioma ),
    CONSTRAINT un_idioma UNIQUE ( nombre )
);

CREATE TABLE genero (
    id_genero VARCHAR2(3) NOT NULL,
    descripcion VARCHAR2(25) NOT NULL,
    CONSTRAINT pk_genero PRIMARY KEY ( id_genero ),
    CONSTRAINT un_genero_descripcion UNIQUE ( descripcion )
);

CREATE TABLE estado_civil (
    id_estado VARCHAR2(2) NOT NULL,
    descripcion VARCHAR2(25) NOT NULL,
    CONSTRAINT pk_estado_civil PRIMARY KEY ( id_estado ),
    CONSTRAINT un_estado_descripcion UNIQUE ( descripcion )
);

CREATE TABLE titulo (
    id_titulo NUMBER(3)
        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre VARCHAR2(60) NOT NULL,
    CONSTRAINT pk_titulo PRIMARY KEY ( id_titulo ),
    CONSTRAINT un_titulo UNIQUE ( nombre )
);

CREATE TABLE personal (
    numrut NUMBER(8) NOT NULL,
    dvrut CHAR(1) NOT NULL,
    p_nombre VARCHAR2(25) NOT NULL,
    s_nombre VARCHAR2(25),
    p_apellido VARCHAR2(25) NOT NULL,
    s_apellido VARCHAR2(25) NOT NULL,
    f_contratacion DATE NOT NULL,
    f_nacimiento DATE NOT NULL,
    email VARCHAR2(100),
    calle VARCHAR2(50) NOT NULL,
    numero NUMBER(5) NOT NULL,
    sueldo NUMBER(5) NOT NULL,
    id_empresa NUMBER(2) NOT NULL,
    id_comuna NUMBER(5) NOT NULL,
    id_genero VARCHAR2(3),
    id_estado VARCHAR2(2),
    e_numrut VARCHAR2(8),
    CONSTRAINT pk_personal PRIMARY KEY ( numrut ),
    CONSTRAINT fk_personal_compania FOREIGN KEY ( id_empresa )
        REFERENCES compania ( id_empresa ),
    CONSTRAINT fk_personal_comuna FOREIGN KEY ( id_comuna )
        REFERENCES comuna ( id_comuna ),
    CONSTRAINT fk_personal_genero FOREIGN KEY ( id_genero )
        REFERENCES genero ( id_genero ),
    CONSTRAINT fk_personal_estado FOREIGN KEY ( id_estado )
        REFERENCES estado_civil ( id_estado ),
    CONSTRAINT fk_personal_personal FOREIGN KEY ( numrut)
        REFERENCES personal ( numrut)
);

CREATE TABLE titulacion (
    id_titulo NUMBER(3) NOT NULL,
    numrut NUMBER(8) NOT NULL,
    fecha_titulo DATE NOT NULL,
    CONSTRAINT fk_titulacion_personal FOREIGN KEY ( numrut )
        REFERENCES personal ( numrut),
    CONSTRAINT fk_titulacion_titulo FOREIGN KEY ( id_titulo )
        REFERENCES titulo ( id_titulo )
);

Create TABLE dominio (
    id_idioma NUMBER(3) NOT NULL, 
    numrut NUMBER(8) NOT NULL,
    nivel VARCHAR2( 25 ) NOT NULL,
    CONSTRAINT fk_dominio_idioma FOREIGN KEY ( id_idioma )
        REFERENCES idioma ( id_idioma ),
    CONSTRAINT fk_dominio_personal FOREIGN KEY ( numrut)
        REFERENCES personal ( numrut )
);

/* ------------------------------------------
   CASO 2: ALTER TABLE
   ------------------------------------------ */

ALTER TABLE personal ADD CONSTRAINT un_personal_email UNIQUE ( email );

ALTER TABLE personal ADD CONSTRAINT ck_personal_dvrut
        CHECK ( dvrut IN ( '0', '1', '2', '3', '4',
                           '5', '6', '7', '8', '9',
                           'K' ) );

-- ALTER TABLE para permitir que el sueldo pueda ser >= 450000
ALTER TABLE personal MODIFY (sueldo NUMBER(7));

ALTER TABLE personal ADD CONSTRAINT ck_personal_sueldo CHECK ( sueldo >= 450000 );

/* ------------------------------------------
   CASO 3: POBLAMIENTO 
   ------------------------------------------ */

CREATE SEQUENCE seq_comuna START WITH 1101 INCREMENT BY 6;

CREATE SEQUENCE seq_compania START WITH 10 INCREMENT BY 5;

/* REGION  */
INSERT INTO region ( nombre ) VALUES ( 'ARICA Y PARINACOTA' );

INSERT INTO region ( nombre ) VALUES ( 'METROPOLITANA' );

INSERT INTO region ( nombre ) VALUES ( 'LA ARAUCANIA' );

/* COMUNA */
INSERT INTO comuna (
    id_comuna,
    nombre,
    id_region
) VALUES ( seq_comuna.NEXTVAL,
           'Arica',
           (
               SELECT
                   id_region
               FROM
                   region
               WHERE
                   nombre = 'ARICA Y PARINACOTA'
           ) );

INSERT INTO comuna (
    id_comuna,
    nombre,
    id_region
) VALUES ( seq_comuna.NEXTVAL,
           'Santiago',
           (
               SELECT
                   id_region
               FROM
                   region
               WHERE
                   nombre = 'METROPOLITANA'
           ) );

INSERT INTO comuna (
    id_comuna,
    nombre,
    id_region
) VALUES ( seq_comuna.NEXTVAL,
           'Temuco',
           (
               SELECT
                   id_region
               FROM
                   region
               WHERE
                   nombre = 'LA ARAUCANIA'
           ) );

/* COMPANIA */
INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'CCyRojas',
           'Amapolas',
           506,
           1857000,
           0.5,
           1101);

INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'SenTTy',
           'Los Alamos',
           3490,
           897000,
           0.025,
           1101);
           
INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'Praxia LTDA',
           'Las Camelias',
           11098,
           2157000,
           0.035,
           1107);

INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'TIC spa',
           'FLORES S.A.',
           4357,
           857000,
           null,
           1107);

INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'SANTANA LTDA',
           'AVDA. VIC. MACKENA',
           106,
           757000,
           0.015,
           1101);
           
INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'FLORES Y ASICIADOS',
           'PEDRO LATORRE',
           557,
           589000,
           0.015,
           1107);

INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'J.A. HOFFMAN',
           'LATINA D.32',
           509,
           1857000,
           0.025,
           1113);
           
INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'CAGLIARI D.',
           'ALAMEDA',
           206,
           1857000,
           null,
           1107);           

INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'Rojas HNOS LTDA',
           'SUCRE',
           106,
           957000,
           0.005,
           1113);

INSERT INTO compania (
    id_empresa,
    nombre,
    calle,
    numero,
    renta,
    porcentaje_aumento,
    id_comuna
) VALUES ( seq_compania.NEXTVAL,
           'FRIENDS P. S.A.',
           'SUECIA',
           506,
           857000,
           0.015,
           1113);

INSERT INTO idioma ( nombre ) VALUES ('Ingles');

INSERT INTO idioma ( nombre ) VALUES ('Chino');

INSERT INTO idioma ( nombre ) VALUES ('Aleman');

INSERT INTO idioma ( nombre ) VALUES ('Espanol');

INSERT INTO idioma ( nombre ) VALUES ('Frances');

/* ------------------------------------------
   CASO 4: CONSULTAS DE INFORMES
   ------------------------------------------ */

SELECT
    nombre AS "Nombre Empresa",
    calle || ' ' || numero AS "Dirección",
    renta AS "Renta Promedio",
    renta * (1 + porcentaje_aumento) "Simulación de Renta"
        FROM compania
        ORDER BY renta DESC, nombre;

SELECT
    id_empresa AS "CODIGO",
    nombre AS "EMPRESA",
    renta AS "PROM RENTA ACTUAL",
    porcentaje_aumento + 0.15 AS "PCT AUMENTADO EN 15%",
    renta * (porcentaje_aumento + 0.15) AS "RENTA AUMENTADA"
    FROM compania
    ORDER BY "PROM RENTA ACTUAL" ASC, "EMPRESA" DESC;

